a=int(input("enter your marks in maths:"))
b=int(input("enter your marks in english:"))
c=int(input("enter your marks in physics:"))
d=int(input("enter your marks in chemistry:"))
e=int(input("enter your marks in biology:"))
f=(a+b+c+d+e)
print(f/5)