a=input("enter the string:")
print("1. To Uppercase")
x=a.isupper()
print(x)
print("2. To Lowercase")
print("3. To Capitalize the First letter")
print("4. Count occurence of a Character")
print("5. Find  a Substring")
print("6. Check if  a string starts with a Substring")
print("7. Check if a String Ends with a Substring")
print("8. Remove Whitespace")
print("9. Replace a Word")